@PostgreSQLConnection_HostAddress = https://localhost:7234


###

POST {{PostgreSQLConnection_HostAddress}}/students
Content-Type: application/json

{
  "name":"John Doe",
  "email":"JOHN@gmail.com"
}

###

@id=1
GET {{PostgreSQLConnection_HostAddress}}/students/{{id}}

###

GET {{PostgreSQLConnection_HostAddress}}/students


###

GET {{PostgreSQLConnection_HostAddress}}/students/passed-out

###

PUT {{PostgreSQLConnection_HostAddress}}/students/{{id}}
Content-Type: application/json

{
  "email":"JohnDoe@gmail.com"
}

###

DELETE {{PostgreSQLConnection_HostAddress}}/students/{{id}}/soft-delete


###
///////////courses
@courseId = 1

POST {{PostgreSQLConnection_HostAddress}}/courses
Content-Type: application/json

{
  "title": "Introduction to Programming",
  "creditHours": 3
}

###

GET {{PostgreSQLConnection_HostAddress}}/courses

###

GET {{PostgreSQLConnection_HostAddress}}/courses/{{courseId}}

###

PUT {{PostgreSQLConnection_HostAddress}}/courses/{{courseId}}
Content-Type: application/json

{
  "description" : "This course provides an introduction to programming concepts and techniques."
}

###


///////////// enrollment
@eid = 1

POST {{PostgreSQLConnection_HostAddress}}/enrollments
Content-Type: application/json

{
  "studentId": 2,
  "courseId": 1
}

###

GET {{PostgreSQLConnection_HostAddress}}/enrollments/{{eid}}

###

GET {{PostgreSQLConnection_HostAddress}}/enrollments

###



DELETE {{PostgreSQLConnection_HostAddress}}/enrollments/{{eid}}

###
